### ISSUE TITLE
'Password slots' are currently blatantly INSECURE, no: **unsecured**

### ISSUE THREAD

**Issue by tuxlifan** [nthdimtech/signet-firmware#26]
Since **anybody** who can get to your Signet for *only a few seconds* can trigger the contents to be typed, they are in their current form **highly insecure** and **misleading**!

The `Password slots` should be *renamed* `Unsecured text slots` for the time being as not to **cause harm to users** trusting in the perceived general security of the Signet (which, pending formal pen testing, for regular use (i.e. with unlocking via password with the client) it would/should have) and not thinking through all consequences!

I'm submitting a separate issue to discuss how this feature might be implemented in a more secure way.

PS: sorry for all the bold screaming but this seems a "sh*t's about to hit the fan" moment to me, both for user's secrets and their trust in the Signet.

**Comment by nthdimtech** [comment]
I think you are over-reacting in terms of the danger. If you know how the feature works then you know that this is, in it's current form, a convenience feature and not a high security feature. If you know that the slots work without a client when you attempt to use it you will also notice you aren't supplying a pin in any way so it's not a difficult inference that to losing physical access compromises the password. The security danger is also a two sided coin, if you choose a stronger password because the Signet is remembering it then that password is more difficult to compromise remotely. Also consider that in some environments local systems are firewall-ed and passwords are weak and written on walls and notes everywhere. Tucking them into a device even without a pin might be a security improvement still.

**Comment by dumblob** [comment]
Please refer to the whole discussion on https://github.com/nthdimtech/signet-desktop-client/issues/22 and then feel free to close this issue.

**Comment by nthdimtech** [comment]
Agreed, lets discuss in one place

**Comment by tuxlifan** [comment]
Yes, it was indeed a very strong reaction -- the combination of "password" and "unconditional access" must have shortened a few neural pathways :)
And worse so since for some reason I hadn't "watch"ed https://github.com/nthdimtech/signet-desktop-client/issues/22 after I found it in the past (when only the first few posts existed) :S my bad.
Closed.
